name: Build & Push Docker Images on Tag

on:
  push:
    tags:
      - 'v*'   # מפעיל את ה-workflow על כל TAG שמתחיל באות v (למשל v1.0.0)

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [ping, pong]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get version (from tag)
        id: vars
        run: echo "VERSION=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT

      - name: Build & Push ${{ matrix.service }}
        uses: docker/build-push-action@v6
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/integrator-engineer-assignment-${{ matrix.service }}:${{ steps.vars.outputs.VERSION }}
            ghcr.io/${{ github.repository_owner }}/integrator-engineer-assignment-${{ matrix.service }}:latest
